### ISSUE TITLE
电报机器人已经安装和连接上容器了，请问如何手动命令，具体方式。

### ISSUE THREAD

**Issue by yydlh** [907739769/xiaoya-sync#4]
十分感谢，另外能给电报bot加上手动执行命令的菜单吗？

**Comment by 907739769** [comment]
/sync和/syncdir,syncdir后面追加指定路径参数可以同步指定路径数据,例如/syncdir 每日更新/电影/中国/

**Comment by 907739769** [comment]
菜单自行在botfather设置
