### ISSUE TITLE
运行三到五次后容器有概率报错

### ISSUE THREAD

**Issue by hulinhao233** [907739769/xiaoya-sync#5]
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /log/java_pid7.hprof ...
Unable to create /log/java_pid7.hprof: File exists
AsyncLogger error handling event seq=261768, value='org.apache.logging.log4j.core.impl.MutableLogEvent@57a69f99': java.lang.OutOfMemoryError: Java heap space

尝试过修改 JAVA_OPTS = -Xms128m -Xmx1024m
没有明显效果

**Comment by 907739769** [comment]
java-pid7.hprof文件打包发我 我分析下

**Comment by hulinhao233** [comment]
http://8.138.58.57:5244/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/java_pid7.zip?sign=XUstecNSqYsaEOIaKOSo-DxogdRQuutc7rsEgrLQD_w=:0
文件太大，用alist传

**Comment by 907739769** [comment]
> http://8.138.58.57:5244/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/java_pid7.zip?sign=XUstecNSqYsaEOIaKOSo-DxogdRQuutc7rsEgrLQD_w=:0 文件太大，用alist传

你是下载了小雅的基础包之后再增量同步的吗   还是一次性全量下载了  我看是着象一次性下载太多文件了

**Comment by hulinhao233** [comment]
> > http://8.138.58.57:5244/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/java_pid7.zip?sign=XUstecNSqYsaEOIaKOSo-DxogdRQuutc7rsEgrLQD_w=:0 文件太大，用alist传
> 
> 你是下载了小雅的基础包之后再增量同步的吗 还是一次性全量下载了 我看是着象一次性下载太多文件了

基础包同步的，就是all.mp4解压的然后用脚本更新，我听小雅说是因为最近在大规模整理资源，所以很多资源要同步，可能是分配的内存还是不够的问题

**Comment by hulinhao233** [comment]
换了xms1g xmx2g后好像没出过问题了
默认512更新量一大就会寄貌似
