### ISSUE TITLE
如何增加执行删除操作的目录

### ISSUE THREAD

**Issue by shmily1866** [907739769/xiaoya-sync#6]
//在这个列表里面的就会执行删除操作
    private List<String> syncList = Arrays.asList("每日更新/.*,电影/2023/.*,纪录片（已刮削）/.*,音乐/演唱会/.*,音乐/狄更斯：音乐剧 (2023)/.*".split(","));

115动漫雅仙女大改了一下，老的文件夹都没删除，看代码是只有上述这些目录会删除过时文件及文件夹，如何添加其他目录执行删除操作？有点菜，容器里翻半天也不知道改哪。

另外看代码，三天一次的全站更新中也没有指定115这个目录，从容器哪里修改呢。

**Comment by 907739769** [comment]
这个我的改代码实现

**Comment by 907739769** [comment]
拉下最新镜像

**Comment by shmily1866** [comment]
> 这个我的改代码实现
佬有空改改吧，最近雅仙女那数据变动挺大的，能不能把所有目录都纳入删除范围，省事。辛苦

**Comment by shmily1866** [comment]
> 拉下最新镜像

真快啊。。。。辛苦😁😁
